# Generated by Django 5.1.6 on 2025-02-17 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0001_initial"),
        ("products", "0003_alter_product_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpricerecord",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productpricerecord",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="products.product"
            ),
        ),
    ]
