# Generated by Django 5.1.6 on 2025-02-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_transaction_currency_transaction_tax_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
