# Generated by Django 5.1.6 on 2025-02-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
