# Generated by Django 5.1.6 on 2025-02-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='processing', max_length=255)),
                ('products', models.ManyToManyField(to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
