# Generated by Django 5.1.6 on 2025-02-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('payment_waiting', 'Payment Waiting'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='payment_waiting', max_length=255),
        ),
    ]
