# Generated by Django 5.1.6 on 2025-02-15 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_cart_items_remove_ordercartitem_order_and_more'),
        ('products', '0002_alter_product_cost_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(to='orders.ordercartitem'),
        ),
        migrations.AddField(
            model_name='ordercartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='ordercartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
