# Generated by Django 5.1.6 on 2025-02-15 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_cart_items_ordercartitem_product_and_more'),
        ('products', '0002_alter_product_cost_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
