# Generated by Django 5.1.6 on 2025-02-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_ordercartitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
