# Generated by Django 5.1.6 on 2025-02-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_cost_alter_product_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
